name: pre-release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle-depen
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('build.gradle') }}-${{ hashFiles('app/build.gradle') }}
      - name: Download Dependencies
        run: ./gradlew androidDependencies
      - name: Test
        run: ./gradlew testReleaseUnitTest
      - name: Publish App Bundle
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > "`pwd`/keystore.jks"
          ./gradlew publishBundle \
            -Pandroid.injected.signing.store.file="`pwd`/keystore.jks" \
            -Pandroid.injected.signing.store.password=$STORE_PASSWORD \
            -Pandroid.injected.signing.key.alias="shared-device-manager" \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
